import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:gas_sensor_app/data/models/models.dart';
import 'package:gas_sensor_app/data/providers.dart';
import 'package:intl/intl.dart';

class InspectionInputScreen extends ConsumerStatefulWidget {
  final EquipmentModel equipment;

  const InspectionInputScreen({super.key, required this.equipment});

  @override
  ConsumerState<InspectionInputScreen> createState() => _InspectionInputScreenState();
}

class _InspectionInputScreenState extends ConsumerState<InspectionInputScreen> {
  final _formKey = GlobalKey<FormState>();
  final _dateController = TextEditingController();
  final _sensitivityController = TextEditingController();
  final _adjBeforeController = TextEditingController();
  final _adjAfterController = TextEditingController();
  String _result = 'OK';
  bool _isSensorReplaced = false;

  @override
  void initState() {
    super.initState();
    _dateController.text = DateFormat('yyyy-MM-dd').format(DateTime.now());
  }

  @override
  void dispose() {
    _dateController.dispose();
    _sensitivityController.dispose();
    _adjBeforeController.dispose();
    _adjAfterController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    final sensitivity = double.tryParse(_sensitivityController.text);
    
    // Rapid Deterioration Check (Mock logic: compare with last inspection)
    // In real app, fetch last inspection here.
    // For demo, let's say if sensitivity < 50% and it wasn't replaced, warn.
    if (sensitivity != null && sensitivity < 50 && !_isSensorReplaced) {
      final confirm = await showDialog<bool>(
        context: context,
        builder: (context) => AlertDialog(
          title: const Text('⚠️ 急激な劣化を検知'),
          content: const Text('前回値と比較して大幅に低下しています。被毒の可能性があります。\nこのまま登録しますか？'),
          actions: [
            TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('キャンセル')),
            TextButton(onPressed: () => Navigator.pop(context, true), child: const Text('登録する', style: TextStyle(color: Colors.red))),
          ],
        ),
      );
      if (confirm != true) return;
    }

    final inspection = InspectionModel(
      id: '', // Generated by DB
      equipmentId: widget.equipment.id,
      inspectionDate: DateTime.parse(_dateController.text),
      gasSensitivity: sensitivity,
      adjustmentBefore: double.tryParse(_adjBeforeController.text),
      adjustmentAfter: double.tryParse(_adjAfterController.text),
      isSensorReplaced: _isSensorReplaced,
      result: _result,
    );

    try {
      await ref.read(gasSensorRepositoryProvider).addInspection(inspection);
      
      // Invalidate providers to refresh UI
      ref.invalidate(siteEquipmentsProvider);
      ref.invalidate(inspectionsProvider(widget.equipment.id));
      ref.invalidate(predictionProvider(widget.equipment.id));
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('点検データを登録しました')));
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('エラー: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('${widget.equipment.tagNo} 点検入力')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _dateController,
                decoration: const InputDecoration(labelText: '点検日'),
                readOnly: true,
                onTap: () async {
                  final date = await showDatePicker(
                    context: context,
                    initialDate: DateTime.now(),
                    firstDate: DateTime(2000),
                    lastDate: DateTime(2100),
                  );
                  if (date != null) {
                    _dateController.text = DateFormat('yyyy-MM-dd').format(date);
                  }
                },
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _sensitivityController,
                decoration: const InputDecoration(labelText: 'ガス感度 (%)', suffixText: '%'),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) return '必須入力です';
                  if (double.tryParse(value) == null) return '数値を入力してください';
                  return null;
                },
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _adjBeforeController,
                      decoration: const InputDecoration(labelText: '調整前値'),
                      keyboardType: TextInputType.number,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextFormField(
                      controller: _adjAfterController,
                      decoration: const InputDecoration(labelText: '調整後値'),
                      keyboardType: TextInputType.number,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<String>(
                // ignore: deprecated_member_use
                value: _result,
                decoration: const InputDecoration(labelText: '総合判定'),
                items: const [
                  DropdownMenuItem(value: 'OK', child: Text('OK')),
                  DropdownMenuItem(value: 'NG', child: Text('NG')),
                ],
                onChanged: (val) => setState(() => _result = val!),
              ),
              const SizedBox(height: 16),
              CheckboxListTile(
                title: const Text('センサー交換実施'),
                value: _isSensorReplaced,
                onChanged: (val) => setState(() => _isSensorReplaced = val!),
              ),
              const SizedBox(height: 32),
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _submit,
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    backgroundColor: Colors.blue,
                    foregroundColor: Colors.white,
                  ),
                  child: const Text('登録', style: TextStyle(fontSize: 18)),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
